services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run start:dev main

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: economic_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
